src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass=UserRepository::class)
 * @ORM\Table(name="`user`")
 */
class User
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Length(min=8,max=8)
     */
    private $cin;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Length(min=3,max=15)
     */
    private $nom;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Length(min=3,max=15)
     */
    private $prenom;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Length(min=5,max=5)
     */
    private $sexe;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Length(min=1,max=3)
     */
    private $age;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Length(min=3,max=15)
     */
    private $Username;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Length(min=8)
     *
     */
    private $mdp;
    /**
     * @Assert\EqualTo(propertyPath="confirm_psw")
     */
    public $confirm_psw;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Length(min=8,max=8)
     */
    private $numtel;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Length(min=3,max=15)
     */
    private $adress;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Length(min=3,max=15)
     */
    private $mail;

    /**
     * @ORM\Column(type="string", length=255, nullable=true, options={"default"="NULL"})
     * @Assert\Length(min=3,max=255)
     */
    private $id_group;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Length(min=10,max=10)
     */
    private $date_inscri;

    /**
     * @ORM\OneToOne(targetEntity=Roles::class, mappedBy="cin", orphanRemoval=true)
     *
     */
    private $role;

    /**
     *
     *
     * @ORM\Column( type="integer", nullable=false, options={"default"=0})
     */

    private $etat;

    /**
     * @return mixed
     */
    public function getEtat()
    {
        return $this->etat;
    }

    /**
     * @param mixed $etat
     */
    public function setEtat($etat): void
    {
        $this->etat = $etat;
    }









    protected $captchaCode;






    public function getId(): ?int
    {
        return $this->id;
    }

    public function getCin(): ?string
    {
        return $this->cin;
    }

    public function setCin(string $cin): self
    {
        $this->cin = $cin;

        return $this;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    public function getPrenom(): ?string
    {
        return $this->prenom;
    }

    public function setPrenom(string $prenom): self
    {
        $this->prenom = $prenom;

        return $this;
    }

    public function getSexe(): ?string
    {
        return $this->sexe;
    }

    public function setSexe(string $sexe): self
    {
        $this->sexe = $sexe;

        return $this;
    }

    public function getAge(): ?string
    {
        return $this->age;
    }

    public function setAge(string $age): self
    {
        $this->age = $age;

        return $this;
    }

    public function getUsername(): ?string
    {
        return $this->Username;
    }

    public function setUsername(string $Username): self
    {
        $this->Username = $Username;

        return $this;
    }

    public function getMdp(): ?string
    {
        return $this->mdp;
    }

    public function setMdp(string $mdp): self
    {
        $this->mdp = $mdp;

        return $this;
    }

    public function getNumtel(): ?string
    {
        return $this->numtel;
    }

    public function setNumtel(string $numtel): self
    {
        $this->numtel = $numtel;

        return $this;
    }

    public function getAdress(): ?string
    {
        return $this->adress;
    }

    public function setAdress(string $adress): self
    {
        $this->adress = $adress;

        return $this;
    }

    public function getMail(): ?string
    {
        return $this->mail;
    }

    public function setMail(string $mail): self
    {
        $this->mail = $mail;

        return $this;
    }

    public function getIdGroup(): ?string
    {
        return $this->id_group;
    }

    public function setIdGroup(?string $id_group): self
    {
        $this->id_group = $id_group;

        return $this;
    }

    public function getDateInscri(): ?string
    {
        return $this->date_inscri;
    }

    public function setDateInscri(string $date_inscri): self
    {
        $this->date_inscri = $date_inscri;

        return $this;
    }

    /**
     * @return mixed
     */
    public function getRole()
    {
        return $this->role;
    }

    /**
     * @param mixed $role
     */
    public function setRole($role): void
    {
        $this->role = $role;
    }
    public function getCaptchaCode()
    {
        return $this->captchaCode;
    }

    public function setCaptchaCode($captchaCode)
    {
        $this->captchaCode = $captchaCode;
    }






}

src/Form/UserType.php
<?php

namespace App\Form;

use App\Entity\User;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Captcha\Bundle\CaptchaBundle\Form\Type\CaptchaType;
use Captcha\Bundle\CaptchaBundle\Validator\Constraints\ValidCaptcha;

class UserType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('cin')
            ->add('nom')
            ->add('prenom')
            ->add('sexe')
            ->add('age')
            ->add('Username')
            ->add('mdp')
            ->add('numtel')
            ->add('adress')
            ->add('mail')
            ->add('role')
            ->add('id_group')
            ->add('date_inscri')
        /*->add('captchaCode', CaptchaType::class, array(
            'captchaConfig' => 'ExampleCaptchaUserRegistration',
            'constraints' => [
                new ValidCaptcha([
                    'message' => 'Invalid captcha, please try again',
                ]),
            ],
        ))*/;

    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => User::class,
        ]);
    }
}

src/Controller/UserController.php
<?php

namespace App\Controller;

use App\Entity\User;
use App\Form\UserType;
use App\Repository\UserRepository;
use Doctrine\ORM\EntityManager;
use Doctrine\ORM\EntityManagerInterface;
use Knp\Component\Pager\PaginatorInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\UX\Chartjs\Builder\ChartBuilderInterface;
use App\Repository\DailyResultRepository;
use Symfony\UX\Chartjs\Model\Chart;


/**
 * @Route("/user")
 */
class UserController extends AbstractController
{
    /**
     * @Route("/", name="user_index", methods={"GET"})
     */
    public function indeex(Request $request , PaginatorInterface $paginator)
    {
        $donnees = $this->getDoctrine()->getRepository(User::class)->findAll();
        $users=$paginator->paginate(
            $donnees,
            $request->query->getInt('page',1),10
        );
        return $this->render('user/index.html.twig', [
            'users' => $users,
        ]);
    }

    /**
     * @Route("/new", name="user_new", methods={"GET", "POST"})
     */
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $user = new User();
        $form = $this->createForm(UserType::class, $user);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {

            $entityManager->persist($user);
            $entityManager->flush();

            return $this->redirectToRoute('user_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('user/new.html.twig', [
            'user' => $user,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="user_show", methods={"GET"})
     */
    public function show(User $user): Response
    {
        return $this->render('user/show.html.twig', [
            'user' => $user,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="user_edit", methods={"GET", "POST"})
     */
    public function edit(Request $request, User $user, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(UserType::class, $user);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('user_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('user/edit.html.twig', [
            'user' => $user,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="user_delete", methods={"POST"})
     */
    public function delete(Request $request, User $user, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$user->getId(), $request->request->get('_token'))) {
            $entityManager->remove($user);
            $entityManager->flush();
        }

        return $this->redirectToRoute('user_index', [], Response::HTTP_SEE_OTHER);
    }
    /**
     * @Route("/e", name="user_etat", methods={"POST"})
     */
    public function etat( $id,EntityManager $entitymanager )
    {

       $user= $this->getDoctrine()->getRepository(User::class)->find($id);
       $user->setEtat(1);
       $entitymanager->persist($user);
        $entitymanager->flush();
        return $this->render('user/index.html.twig', [
            'controller_name' => 'UserController',
        ]);
        /*return new Response($user->getNom().'has been blocked',$this->render('user/index.html.twig'))
        ;*/
    }


}

templates/user/_delete_form.html.twig
<form method="post" action="{{ path('user_delete', {'id': user.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ user.id) }}">
    <button class="btn">Delete</button>
</form>

templates/user/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}

    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/user/charts.html.twig
{% extends 'base2.html.twig' %}
{% block title %}Hello ChartjsController!{% endblock %}

{% block body %}
    <style>
        .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
        .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
    </style>

    <div class="example-wrapper">
        {{ render_chart(chart, {'id': 'my-chart'})}}
    </div>
{% endblock %}

templates/user/edit.html.twig
{% extends 'base2.html.twig' %}

{% block title %}Edit User{% endblock %}

{% block body %}
    <h1>Edit User</h1>

    {{ include('user/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('user_index') }}">back to list</a>

    {{ include('user/_delete_form.html.twig') }}
{% endblock %}

templates/user/index.html.twig
{% extends 'base2.html.twig' %}

{% block title %}User index{% endblock %}

{% block body %}
    <h1>User index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Cin</th>
                <th>Nom</th>
                <th>Prenom</th>
                <th>Sexe</th>
                <th>Age</th>
                <th>Username</th>
                <th>Mdp</th>
                <th>Numtel</th>
                <th>Adress</th>
                <th>Mail</th>
                <th>Id_group</th>
                <th>role</th>
                <th>Date_inscri</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for user in users %}

            <tr>
                <td>{{ user.id }}</td>
                <td>{{ user.cin }}</td>
                <td>{{ user.nom }}</td>
                <td>{{ user.prenom }}</td>
                <td>{{ user.sexe }}</td>
                <td>{{ user.age }}</td>
                <td>{{ user.Username }}</td>
                <td>{{ user.mdp }}</td>
                <td>{{ user.numtel }}</td>
                <td>{{ user.adress }}</td>
                <td>{{ user.mail }}</td>
                <td>{{ user.idGroup }}</td>
                <td>
                    {{ user.role }}
                </td>
                <td>{{ user.dateInscri }}</td>
                <td>
                    <a href="{{ path('user_show', {'id': user.id}) }}">show</a>
                    <a href="{{ path('user_edit', {'id': user.id}) }}">edit</a>
                    {% if user.etat==0 %}
                    <a href="{{ path('user_etat', {'id': user.id}) }}"onclick="return confirm('Are you sure you want to block this user ?')
                                        ">block</a>
                    {% elseif user.etat==1%}
                        <a href=""onclick="return confirm('Are you sure you want to unblock this user ?')
                                        " href="">unblock</a>
                    {% endif %}
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="14">no records found</td>
            </tr>
        {% endfor %}
        {{ knp_pagination_render(users) }}
        </tbody>
    </table>


{% endblock %}

templates/user/new.html.twig
{% extends 'base2.html.twig' %}

{% block title %}New User{% endblock %}

{% block body %}
    <h1>Create new User</h1>

    {{ include('user/_form.html.twig') }}
    <!--<div class="row">
        <div class="col-md-4 offset-md-4">
            <div class="form-group">
                <label for="exampleFormControlInput1">Are you a robot?</label>
                "form_widget(registrationForm.captchaCode,{'attr':{'class':'form-control'}})"
            </div>
        </div>
    </div>
     form_row(registrationForm.captchaCode) -->
    <a href="{{ path('user_index') }}">back to list</a>
{% endblock %}

templates/user/show.html.twig
{% extends 'base2.html.twig' %}

{% block title %}User{% endblock %}

{% block body %}
    <h1>User</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ user.id }}</td>
            </tr>
            <tr>
                <th>Cin</th>
                <td>{{ user.cin }}</td>
            </tr>
            <tr>
                <th>Nom</th>
                <td>{{ user.nom }}</td>
            </tr>
            <tr>
                <th>Prenom</th>
                <td>{{ user.prenom }}</td>
            </tr>
            <tr>
                <th>Sexe</th>
                <td>{{ user.sexe }}</td>
            </tr>
            <tr>
                <th>Age</th>
                <td>{{ user.age }}</td>
            </tr>
            <tr>
                <th>Username</th>
                <td>{{ user.Username }}</td>
            </tr>
            <tr>
                <th>Mdp</th>
                <td>{{ user.mdp }}</td>
            </tr>
            <tr>
                <th>Numtel</th>
                <td>{{ user.numtel }}</td>
            </tr>
            <tr>
                <th>Adress</th>
                <td>{{ user.adress }}</td>
            </tr>
            <tr>
                <th>Mail</th>
                <td>{{ user.mail }}</td>
            </tr>
            <tr>
                <th>Id_group</th>
                <td>{{ user.idGroup }}</td>
            </tr>
            <tr>
                <th>role</th>
                <td>{{ user.id }}</td>
            </tr>
            <tr>
                <th>Date_inscri</th>
                <td>{{ user.dateInscri }}</td>
            </tr>
        </tbody>
    </table>



        <a class="nav-link" href="{{ path('user_index') }}">
            <i class="fas fa-fw fa-tachometer-alt"></i>
            <span>Back to list</span></a>
        </a>


    <a class="nav-link" href="{{ path('user_edit', {'id': user.id}) }}">
        <i class="fas fa-fw fa-tachometer-alt"></i>
        <span>edit</span></a>
    </a>

    {{ include('user/_delete_form.html.twig') }}
{% endblock %}